quarkus.application.name=quarkus-application
quarkus.application.version=1.0.0
quarkus.http.port=8081
quarkus.http.root-path=/api
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=passpass
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/demo_quarkus
quarkus.http.auth.permission.authenticated.paths=/*
quarkus.http.auth.permission.authenticated.policy=authenticated

quarkus.oidc.auth-server-url=http://localhost:8080/realms/quarkus-realm
quarkus.oidc.client-id=quarkus-app
quarkus.oidc.credentials.secret=M5xhRFyufAmSCS9yoJKR23GYlW06cNt5
quarkus.smallrye-jwt.enabled=true
quarkus.http.auth.proactive = false
quarkus.oidc.tls.verification=none
quarkus.oidc.application-type=service
# quarkus.oidc.roles.source="access-token"




